### ISSUE TITLE
update the home page

### ISSUE THREAD

**Issue by cartoloupe** [paircolumbus/MediaCollection#3]
@degoeym Let's update the home page so that it does not display the default Rails app page

**Comment by degoeym** [comment]
What do you think we should update it to look like?

**Comment by cartoloupe** [comment]
I was thinking something really basic for now, just to figure where to set the view up, maybe something like this:

![screen shot 2014-09-20 at 12 08 44 pm](https://cloud.githubusercontent.com/assets/4593934/4345787/b3ba0cb0-40e0-11e4-867e-33760648ff7f.png)

**Comment by degoeym** [comment]
Think that should be possible. I pushed up a couple of static pages, which is what I'm working on now with the Rails Tutorial book. Not sure that's how we want them done, though. You can see the commits in my degoeym branch. 

I'll try to get this page at least built this weekend.

**Comment by cartoloupe** [comment]
Sounds good. The static pages part of the tutorial was what I had in mind for where to go to look up how to do this. In the later chapters about signing up, they switch over to a dynamic page, which we'll probably do as well. 

Let me know when you cut a PR for the branch, looks good so far.

**Comment by degoeym** [comment]
I went ahead and added some very rudimentary markup to my degoeym branch for the home.html.erb page. Nothing is stylized, just threw something up there. I'm still going to work on making it simply be "localhost:3000/home" instead of "localhost:3000/static_pages/home".

**Comment by degoeym** [comment]
Updated both the Home and Help pages to work off application.html.erb, per the end of chapter 3.

**Comment by cartoloupe** [comment]
Pulled that branch, spun up `rails s`, and went to `localhost:3000/static_pages/home`:

![screen shot 2014-09-20 at 8 07 39 pm](https://cloud.githubusercontent.com/assets/4593934/4346956/b2230b02-4123-11e4-856d-0bb63d7dd4fe.png)

Looks good! I think chapter 4 breaks from Rails and goes into Ruby, and might complement the other drills that we are doing. It might be a good time to merge this branch into master.

Chapter 5 dealt with layouts and testing layouts. I skimmed over it and went to the user model and signup logic in Chapter 6, but ended up going back to 5 for details that 6 built on. After 6, an "items" or "media" model should be able to be set up, with the ability to CRUD them.

**Comment by degoeym** [comment]
Cool beans. I'll merge it into master either later tonight or tomorrow.

**Comment by degoeym** [comment]
I've merged degoeym with master.

**Comment by degoeym** [comment]
Just made my way through chapter 4 tonight. Sort of skimmed through it as a good chunk of the ruby code I was already able to read pretty well. On to chapter 5 tomorrow night.

**Comment by cartoloupe** [comment]
Great. Let's use some of the styling that is covered in chapter 5 to style the home page and help pages (i.e. bootstrap and sass).

Also, at this point it should be pushable to heroku. We should probably give that a shot and see what we run into.

**Comment by degoeym** [comment]
I'm up to chapter 5.2. Didn't get through as much of the book tonight as I'd hoped. Been one of those days at work. I'll finish up the chapter tomorrow night and try to apply the lessons to this project as well. Barring any issues I'm hoping to be through at least chapter 6, possibly 7 by the time we meet on Saturday so we can start to do some real damage.

**Comment by degoeym** [comment]
Alright, I have VERY rough Bootstrap layout styling for the site so far. Some links are a little messed up, and I need to apply the routing changes, but I managed to pretty it up a bit.

Looks like I may have to go back and do some things in the updated edition of the book. The nav items for the ul weren't working until I loaded the same chapter for the latest edition and found I had to add navbar-nav to the class listing for the unordered list.

I'll work on getting the routing tidied up, then deploying to Heroku in the next day or two unless you want to take a crack at something.

Changes are in the update-layout branch.

**Comment by degoeym** [comment]
Alright, routes have been updated. Pushed the changes to the update-layout branch. Give it a look over and tell me what you think.

I haven't pushed it to Heroku yet as I don't know if you want me to just push it to mine, or if we should create a joint Heroku account or what.

**Comment by degoeym** [comment]
Pushed it up to Heroku to test.

http://dry-crag-8914.herokuapp.com/

**Comment by cartoloupe** [comment]
Nice work! Site looks great.

I have a few questions on the routes setup; if you can create the pull request for the update-layout branch I'll comment right in the diff. 

I couldn't think of any layout-related things to add myself, so I think we should merge ahead. I am working through a jQuery tutorial, so maybe we can brainstorm some extra javascript features after the basics are covered.

**Comment by degoeym** [comment]
Thanks. Sorry it took longer than expected. 

Just did the pull request. Hope I did it right.

**Comment by cartoloupe** [comment]
No worries, I think the pace is good. I am commenting in the PR now; let me know if you can see my questions.

**Comment by degoeym** [comment]
Blarg, mobile app won't let me reply to any of your code comments. Stupid mobile app.

**Comment by degoeym** [comment]
So is this an issue we can close now?

**Comment by cartoloupe** [comment]
Yep, closing now.
